version: '3'

services:
  client:
    build:
      context: "."
      dockerfile: "./docker/Dockerfile"
    container_name: openlab-admin
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5173:5173"